# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd784b023c1d46b3a85d838d043a413a6ed57bf3f916cdeacdaa2a1b64aa3f42916fbcfd72cbeda71a5febf1a3e7ad2f7eace17076f843944a5d39e76bb4e0e8

test:
  secret_key_base: 9413c1c790ed97aef0af9b7b7b8f71c159dde96a9f89dc2c54b413a85e9278f1413abdc4d73f7bc28aee8d6a4d9a13ea1b43abeffecf5ce3a5cdebb1cdad82f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
